version: "3"

services:
  webserver:
    build:
      context: ./config/web
    container_name: 'web-server'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DOCUMENT_ROOT-./html/www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./data/logs/apache2}:/var/log/apache2
  mysql:
    build: ./config/mysql
    container_name: 'mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./data/logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8443:8081'
    volumes:
      - /sessions

